// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uketoloskunayanndlae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZXRvbG9za3VuYXlhbm5kbGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjc3NjEsImV4cCI6MjA2MTc0Mzc2MX0.LpG7O2L5QXcu1TTgi-18z5sXq2E5ez4W2uKYXQLi8Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);